### ISSUE TITLE
Type 'Owin.OwinRequestScopeContext' is not marked as serializable.

### ISSUE THREAD

**Issue by Kahbazi** [neuecc/OwinRequestScopeContext#2]
when I'm using this code
`System.AppDomain.CurrentDomain.Evidence`

I get this exception

> "Type 'Owin.OwinRequestScopeContext' in assembly 'OwinRequestScopeContext, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable."

**Comment by nickwinger** [comment]
why this was closed ? i have the same problem..
